import type { Route as _IndexRoute } from '../pages/';
/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import type { Route as _AboutRoute } from '../pages/about';
import type { Route as _AddFoodRoute } from '../pages/add-food';
import type { Route as _CalendarRoute } from '../pages/calendar';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/add-food': (typeof _AddFoodRoute)['_inputType'];
    '/calendar': (typeof _CalendarRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/add-food': (typeof _AddFoodRoute)['_outputType'];
    '/calendar': (typeof _CalendarRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
